sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qtdeclarative5-dev qttools5-dev-tools #install necessary Qt file

script:
  - g++ -v
  - qmake tanks.pro
  - make
  - ./src/tests/tst_tankstest

after_success:
  - coveralls  --verbose
