sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qtdeclarative5-dev qttools5-dev-tools #install necessary Qt file
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ./tests/tests
  - cd ..
  - coveralls --exclude-pattern ".*/build/*" --exclude-pattern ".*/3rdParty/*"
