sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qtdeclarative5-dev qttools5-dev-tools #install necessary Qt files

script:
  - qmake "DESTDIR+=build" tanks/tanks.pro
  - make

language: cpp
